# Generated by Django 5.1.4 on 2025-03-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
