# Generated by Django 5.1.4 on 2025-03-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_node_api_url_alter_node_ip_alter_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='capacity_gb',
            field=models.FloatField(default=10.0),
        ),
    ]
